// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRowqE4u1uXcT_cFSYtk5pHQhOzF9BPg',
    appId: '1:606198864287:android:6e30a76f041ead583a45aa',
    messagingSenderId: '606198864287',
    projectId: 'bsty-68d37',
    storageBucket: 'bsty-68d37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt7IXKXC0PY3Zx56jILaRKCdGRseTOlj8',
    appId: '1:606198864287:ios:6d4637303f2cea373a45aa',
    messagingSenderId: '606198864287',
    projectId: 'bsty-68d37',
    storageBucket: 'bsty-68d37.firebasestorage.app',
    androidClientId: '606198864287-17t8jkuuk68rcv6qkm6582sr4s2284e1.apps.googleusercontent.com',
    iosClientId: '606198864287-s4skcpk3qu4pgrgvuthado9splnftp0u.apps.googleusercontent.com',
    iosBundleId: 'com.wedconnect.bsty',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVC55oCprMNxLvKTWUfAOxJNhB3dLykTQ',
    appId: '1:606198864287:web:f1368a79aa7de8273a45aa',
    messagingSenderId: '606198864287',
    projectId: 'bsty-68d37',
    authDomain: 'bsty-68d37.firebaseapp.com',
    storageBucket: 'bsty-68d37.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt7IXKXC0PY3Zx56jILaRKCdGRseTOlj8',
    appId: '1:606198864287:ios:6d4637303f2cea373a45aa',
    messagingSenderId: '606198864287',
    projectId: 'bsty-68d37',
    storageBucket: 'bsty-68d37.firebasestorage.app',
    androidClientId: '606198864287-17t8jkuuk68rcv6qkm6582sr4s2284e1.apps.googleusercontent.com',
    iosClientId: '606198864287-s4skcpk3qu4pgrgvuthado9splnftp0u.apps.googleusercontent.com',
    iosBundleId: 'com.wedconnect.bsty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVC55oCprMNxLvKTWUfAOxJNhB3dLykTQ',
    appId: '1:606198864287:web:f9008e4905c7b3063a45aa',
    messagingSenderId: '606198864287',
    projectId: 'bsty-68d37',
    authDomain: 'bsty-68d37.firebaseapp.com',
    storageBucket: 'bsty-68d37.firebasestorage.app',
  );

}